#!/usr/bin/env bash
# req-add-submodule.sh — install req framework into an existing repo as a submodule
#
# Usage (run from the host repo root):
#   git submodule add https://github.com/adamou0408/req .req-framework
#   bash .req-framework/framework/scripts/req-add-submodule.sh \
#        [--data-root=.req] [--code-root=.] [--non-interactive]
#
# This is the zero-invasive installer for existing projects:
#   - business data lives in <data_root> (default: .req)
#   - AI-generated code lands in <code_root>/src and <code_root>/tests (default: . — host's real src/)
#   - the framework itself lives in .req-framework (the submodule)
#
# Existing files in the host repo are NOT touched.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST="$(pwd)"

DATA_ROOT=".req"
CODE_ROOT="."
INTERACTIVE=1

for arg in "$@"; do
    case "$arg" in
        --data-root=*) DATA_ROOT="${arg#--data-root=}" ;;
        --code-root=*) CODE_ROOT="${arg#--code-root=}" ;;
        --non-interactive) INTERACTIVE=0 ;;
        -h|--help)
            sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "Unknown arg: $arg" >&2; exit 1 ;;
    esac
done

if [ ! -d "$HOST/.req-framework" ]; then
    echo "ERROR: .req-framework submodule not found." >&2
    echo "       Run first: git submodule add https://github.com/adamou0408/req .req-framework" >&2
    exit 1
fi

if [ -f "$HOST/.req.config.yml" ]; then
    echo "ERROR: .req.config.yml already exists. Already installed." >&2
    exit 1
fi

if [ "$INTERACTIVE" = "1" ]; then
    echo "Installing req framework into existing repo: $HOST"
    echo ""
    read -r -p "Where should business data (intake/specs/personas/...) live? [$DATA_ROOT]: " ans
    [ -n "$ans" ] && DATA_ROOT="$ans"
    read -r -p "Where should AI-generated code (src/, tests/) live? [$CODE_ROOT — your real src/]: " ans
    [ -n "$ans" ] && CODE_ROOT="$ans"
    echo ""
    echo "Summary:"
    echo "  data_root      = $DATA_ROOT"
    echo "  code_root      = $CODE_ROOT"
    echo "  framework_root = .req-framework"
    read -r -p "Proceed? [Y/n]: " ans
    if [ "${ans:-Y}" != "Y" ] && [ "${ans:-y}" != "y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

FW_VERSION="$(cat "$HOST/.req-framework/VERSION" 2>/dev/null || echo unknown)"

cat > "$HOST/.req.config.yml" <<EOF
# req framework configuration (generated by req-add-submodule.sh)
data_root: $DATA_ROOT
code_root: $CODE_ROOT
framework_root: .req-framework
autonomy_level: strict
last_synced_version: $FW_VERSION
EOF

echo "→ Creating business directories under $DATA_ROOT/"
mkdir -p "$HOST/$DATA_ROOT/intake/raw" \
         "$HOST/$DATA_ROOT/specs" \
         "$HOST/$DATA_ROOT/personas" \
         "$HOST/$DATA_ROOT/conflicts" \
         "$HOST/$DATA_ROOT/reviews" \
         "$HOST/$DATA_ROOT/docs/postmortems"

touch "$HOST/$DATA_ROOT/intake/raw/.gitkeep" \
      "$HOST/$DATA_ROOT/specs/.gitkeep" \
      "$HOST/$DATA_ROOT/personas/.gitkeep" \
      "$HOST/$DATA_ROOT/conflicts/.gitkeep" \
      "$HOST/$DATA_ROOT/reviews/.gitkeep"

if [ ! -f "$HOST/$DATA_ROOT/docs/changelog.md" ]; then
    cat > "$HOST/$DATA_ROOT/docs/changelog.md" <<EOF
# Changelog

This file logs every spec state transition.

## $(date '+%Y-%m-%d')
- req framework installed via req-add-submodule.sh (v$FW_VERSION)
EOF
fi

# Install .claude/settings.json (skip if user already has one)
SETTINGS_TEMPLATE="$HOST/.req-framework/framework/templates/settings.json"
if [ -f "$SETTINGS_TEMPLATE" ]; then
    mkdir -p "$HOST/.claude"
    if [ ! -f "$HOST/.claude/settings.json" ]; then
        sed \
            -e "s|\${REQ_DATA_ROOT}|${DATA_ROOT}|g" \
            -e "s|\${REQ_CODE_ROOT}|${CODE_ROOT}|g" \
            -e "s|\${REQ_FRAMEWORK_ROOT}|.req-framework|g" \
            "$SETTINGS_TEMPLATE" > "$HOST/.claude/settings.json"
        echo "→ Installed .claude/settings.json (permissions only)"
    else
        echo "⚠ .claude/settings.json already exists — skipped (merge .req-framework/framework/templates/settings.json manually if needed)"
    fi
fi

echo "→ Generating .claude/commands/req-*.md and .claude/agents/req-*.md"
bash "$HOST/.req-framework/framework/scripts/req-sync-commands.sh"

cat <<EOF

✅ req framework installed (zero-invasive).

What was added:
  - .req.config.yml             (config — commit this)
  - $DATA_ROOT/                 (business data — commit this)
  - .claude/commands/req-*.md   (auto-generated slash commands — commit this)
  - .claude/agents/req-*.md     (auto-generated subagents — commit this)
  - .claude/settings.json       (permissions only, only if you didn't already have one)

What was NOT touched:
  - your existing src/, tests/, README.md, CI, .gitignore main body

Next steps:
  1. git add .req.config.yml $DATA_ROOT .claude/commands/req-*.md .claude/agents/req-*.md .claude/settings.json
  2. git commit -m "chore: install req framework (v$FW_VERSION)"
  3. Open Claude Code and run /req-intake

Upgrade later with:
  git submodule update --remote .req-framework
  bash .req-framework/framework/scripts/req-sync-commands.sh
EOF
